# Generated by Django 5.2.8 on 2025-11-29 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='rostos/')),
                ('nome', models.CharField(max_length=255)),
                ('faculdade', models.CharField(max_length=255)),
                ('ra', models.IntegerField()),
                ('curso', models.CharField(max_length=255)),
                ('turno', models.CharField(max_length=20)),
                ('emitido', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('curso', models.CharField(max_length=255)),
                ('status', models.BooleanField()),
                ('face_ou_cartao', models.BooleanField()),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
