# Generated by Django 5.2.8 on 2025-11-30 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_aluno_ra'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatorio',
            name='faculdade',
            field=models.CharField(default='exit', max_length=255),
            preserve_default=False,
        ),
    ]
