# Generated by Django 5.2.8 on 2025-11-30 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_relatorio_faculdade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatorio',
            name='faculdade',
            field=models.CharField(max_length=255),
        ),
    ]
