# Generated by Django 5.2.8 on 2025-11-30 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_relatorio_faculdade'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatorio',
            name='turno',
            field=models.CharField(default='Tarde', max_length=20),
        ),
    ]
