# Generated by Django 5.2.8 on 2025-11-30 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_relatorio_turno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatorio',
            name='turno',
            field=models.CharField(max_length=20),
        ),
    ]
