# Generated by Django 5.2.8 on 2025-11-30 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_relatorio_turno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='emitido',
            field=models.DateField(null=True),
        ),
    ]
