# Generated by Django 5.2.8 on 2025-12-01 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_aluno_emitido'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='encoding',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
